language: python
python:
  - 3.5.0
  - 3.5.2
  - 3.6
sudo: false

matrix:
  include:
    - os: osx
      language: generic
      env: MACPYTHON=3.5.2
    - os: osx
      language: generic
      env: MACPYTHON=3.6.0

script:
  - ./.travis.sh
