language: python
python:
  - 3.5.0
  - 3.5.3
  - 3.6
sudo: false

matrix:
  include:
    - os: linux
      language: generic
      env: USE_PYPY_NIGHTLY=1
    - os: osx
      language: generic
      env: MACPYTHON=3.5.3
    - os: osx
      language: generic
      env: MACPYTHON=3.6.0
  allow_failures:
    - env: USE_PYPY_NIGHTLY=1

script:
  - ./.travis.sh
